name: Get info on runner
run-name: Runner info
on: 
  # needs to be started manually
  workflow_dispatch:
jobs:
  Runner-Info-RAM-CPU:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶"
      - run: lscpu
      - run: echo "ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶  ğŸ”¶"
      - run: free -h
      - run: cat /etc/os-release
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: echo "ğŸ‰ Woohoo! Your action is complete! Have an amazing day and happy coding! ğŸš€"
