name: Test Github Actions workflow_call.inputs
run-name: Testing actions on.workflow_call.inputs ğŸ”
# work in progress
# this action runs two jobs: Job1 and Job2
## see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
## Use on.workflow_call to define the inputs and outputs for a reusable workflow
## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_callinputs
on:
  workflow_call:
    inputs:
      inputstring:
        description: 'A string passed from the caller workflow'
        default: 'myString'
        required: false
        type: string

jobs:
  Job1-print-input-string:
    runs-on: ubuntu-latest

    steps:
      - name: Print the string to STDOUT
        run: echo The string is ${{ inputs.inputstring }}
        
  Job2-List-Notebook-Files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/*.ipynb
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  
